"""Create cat persona table

Revision ID: 72935130eace
Revises: ee74cf3cf089
Create Date: 2024-12-30 16:24:08.189607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72935130eace'
down_revision: Union[str, None] = 'ee74cf3cf089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_personas',
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('persona_id')
    )
    op.add_column('chats', sa.Column('persona_id', sa.String(), nullable=False))
    op.create_foreign_key('fk_chat_cat_persona', 'chats', 'cat_personas', ['persona_id'], ['persona_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_cat_persona', 'chats', type_='foreignkey')
    op.drop_column('chats', 'persona_id')
    op.drop_table('cat_personas')
    # ### end Alembic commands ###
